---
include:
  - board: nice_nano_v2
    shield: Lily58_L nice_oled
    artifact-name: left_oled
  - board: nice_nano_v2
    shield: Lily58_R nice_oled
    artifact-name: right-oled
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
