---
include:
  - board: nice_nano_v2
    shield: Lily58_L nice_oled nice_view_gem
  - board: nice_nano_v2
    shield: Lily58_R nice_oled nice_view_gem
  - board: nice_nano_v2
    shield: settings_reset
